[build]
  functions = "netlify/functions"
  publish = "public"

# Redirige /api/convert-distance -> función convert-distance, etc.
[[redirects]]
  from = "/api/convert-distance"
  to = "/.netlify/functions/convert-distance"
  status = 200

[[redirects]]
  from = "/api/convert-temperature"
  to = "/.netlify/functions/convert-temperature"
  status = 200

[[redirects]]
  from = "/api/convert-weight"
  to = "/.netlify/functions/convert-weight"
  status = 200
